services:
  vehicle-detection-api:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: vehicle-detection-api
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
    volumes:
      - ../artifacts/models:/app/artifacts/models
      - ../artifacts/metrics:/app/artifacts/metrics:ro
      - ../logs:/app/logs
    restart: unless-stopped